# Infinispan connection
infinispan.remote.server-list=127.0.0.1:11222
infinispan.remote.auth-username=admin
infinispan.remote.auth-password=password

# Spring AI Infinispan vector store
spring.ai.vectorstore.infinispan.store-name=spring-ai-embeddings
spring.ai.vectorstore.infinispan.similarity=COSINE
spring.ai.vectorstore.infinispan.create-store=true
spring.ai.vectorstore.infinispan.distance=3
