# LangChain4j Infinispan embedding store configuration
quarkus.langchain4j.infinispan.dimension=384
quarkus.langchain4j.infinispan.cache-name=langchain4j-embeddings
quarkus.langchain4j.infinispan.distance=3
quarkus.langchain4j.infinispan.similarity=COSINE
quarkus.langchain4j.infinispan.create-cache=true

# Uncomment if you are running a server locally
# quarkus.infinispan-client.devservices.enabled=false
# quarkus.infinispan-client.hosts=localhost:11222
# quarkus.infinispan-client.username=admin
# quarkus.infinispan-client.password=password

# Assumes a server is running, with admin/password, locally
%prod.quarkus.infinispan-client.hosts=localhost:11222
%prod.quarkus.infinispan-client.username=admin
%prod.quarkus.infinispan-client.password=password
